name: Check Style Code

on:
  push:
    branches:
      - vetka

  pull_request:
    branches:
      - vetka

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      # Загрузка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404' # Укажите нужную версию SDK

      # Установка StyleCop.Analyzers
      - name: Install StyleCop.Analyzers
        run: |
          dotnet add package StyleCop.Analyzers --prerelease

      # Сборка проекта (обязательно перед анализом)
      - name: Build project
        run: |
          dotnet build --no-restore

      # Проверка стиля кода с помощью StyleCop
      - name: Run StyleCop Analysis
        run: |
          dotnet build -warnaserror
